#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kpty
Version  : 5.75.0
Release  : 32
URL      : https://download.kde.org/stable/frameworks/5.75/kpty-5.75.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.75/kpty-5.75.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/5.75/kpty-5.75.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: kpty-data = %{version}-%{release}
Requires: kpty-lib = %{version}-%{release}
Requires: kpty-license = %{version}-%{release}
Requires: kpty-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : kcoreaddons-dev
BuildRequires : ki18n-dev
BuildRequires : qtbase-dev mesa-dev

%description
# KPty
Interfacing with pseudo terminal devices
## Introduction
This library provides primitives to interface with pseudo terminal devices
as well as a KProcess derived class for running child processes and
communicating with them using a pty.

%package data
Summary: data components for the kpty package.
Group: Data

%description data
data components for the kpty package.


%package dev
Summary: dev components for the kpty package.
Group: Development
Requires: kpty-lib = %{version}-%{release}
Requires: kpty-data = %{version}-%{release}
Provides: kpty-devel = %{version}-%{release}
Requires: kpty = %{version}-%{release}

%description dev
dev components for the kpty package.


%package lib
Summary: lib components for the kpty package.
Group: Libraries
Requires: kpty-data = %{version}-%{release}
Requires: kpty-license = %{version}-%{release}

%description lib
lib components for the kpty package.


%package license
Summary: license components for the kpty package.
Group: Default

%description license
license components for the kpty package.


%package locales
Summary: locales components for the kpty package.
Group: Default

%description locales
locales components for the kpty package.


%prep
%setup -q -n kpty-5.75.0
cd %{_builddir}/kpty-5.75.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602617192
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1602617192
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kpty
cp %{_builddir}/kpty-5.75.0/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kpty/e712eadfab0d2357c0f50f599ef35ee0d87534cb
cp %{_builddir}/kpty-5.75.0/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kpty/20079e8f79713dce80ab09774505773c926afa2a
pushd clr-build
%make_install
popd
%find_lang kpty5

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories5/kpty.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KPty/KPty
/usr/include/KF5/KPty/KPtyDevice
/usr/include/KF5/KPty/KPtyProcess
/usr/include/KF5/KPty/kpty.h
/usr/include/KF5/KPty/kpty_export.h
/usr/include/KF5/KPty/kptydevice.h
/usr/include/KF5/KPty/kptyprocess.h
/usr/include/KF5/kpty_version.h
/usr/lib64/cmake/KF5Pty/KF5PtyConfig.cmake
/usr/lib64/cmake/KF5Pty/KF5PtyConfigVersion.cmake
/usr/lib64/cmake/KF5Pty/KF5PtyTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5Pty/KF5PtyTargets.cmake
/usr/lib64/libKF5Pty.so
/usr/lib64/qt5/mkspecs/modules/qt_KPty.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5Pty.so.5
/usr/lib64/libKF5Pty.so.5.75.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kpty/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kpty/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f kpty5.lang
%defattr(-,root,root,-)

